name: Deploy Blog

on:
  push:
    branches: [master]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: 117.72.149.211
          username: root
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            cd /var/www/hexo
            git pull origin master
            npm install --prefer-offline
            npx hexo generate
